### ISSUE TITLE
Home assistant repository

### ISSUE THREAD

**Issue by ffries** [gi1mic/gmc320#1]
Hello,

First I would like to thank you for this add-on.
I own a gmc320 and would like to install it in HA.

Here is my question:
How to add this project to HA?
I am running a RaspberryPi 3B with HA.

I don't have SSH access as I used rpi-imager to create the HA installation.

Can I add this project as a repository in HA?
Please advise.

Kind regards,
Ffries

**Comment by ffries** [comment]
Got it:
I need SSH addon.
There is an addon directory and this is where I shall put all files.

**Comment by ffries** [comment]
Closing installation works.

**Comment by bobofruit1970** [comment]
@ffries How to install this addon.
What do You mean when You say Closing installation works.
I do not understand how to install it. The same as You.

Someone has worked hard and doesn't even realize that many people don't know how to use it.
