### ISSUE TITLE
s6-supervise gmc320 (child): fatal: unable to exec run: Permission denied

### ISSUE THREAD

**Issue by ffries** [gi1mic/gmc320#2]
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
Hello,

First many thanks for working on the project.

Could you help with my setup:
HA on RaspberryPi installed
GMC 3x module installed via SSH in add-ons folder
serial not installed (I don't know how to proceed)

Here is the log
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun gmc320 (no readiness notification)
s6-supervise gmc320 (child): fatal: unable to exec run: Permission denied
s6-supervise gmc320: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise gmc320 (child): fatal: unable to exec run: Permission denied
s6-supervise gmc320: warning: unable to spawn ./run - waiting 10 seconds

**Comment by ffries** [comment]
This was fixed when I added serial, but I prefer to leave this open.
This should be done by the module automatically.

**Comment by ffries** [comment]
Closing it.

**Comment by phoenixckua** [comment]
> s6-rc: info: service s6rc-oneshot-runner: starting s6-rc: info: service s6rc-oneshot-runner successfully started Hello,
> 
> First many thanks for working on the project.
> 
> Could you help with my setup: HA on RaspberryPi installed GMC 3x module installed via SSH in add-ons folder serial not installed (I don't know how to proceed)
> 
> Here is the log s6-rc: info: service fix-attrs: starting s6-rc: info: service fix-attrs successfully started s6-rc: info: service legacy-cont-init: starting s6-rc: info: service legacy-cont-init successfully started s6-rc: info: service legacy-services: starting services-up: info: copying legacy longrun gmc320 (no readiness notification) s6-supervise gmc320 (child): fatal: unable to exec run: Permission denied s6-supervise gmc320: warning: unable to spawn ./run - waiting 10 seconds s6-supervise gmc320 (child): fatal: unable to exec run: Permission denied s6-supervise gmc320: warning: unable to spawn ./run - waiting 10 seconds

How U fix it?

**Comment by bobofruit1970** [comment]
@ffries How did You get serial number?

**Comment by CinciRyan** [comment]
@ffries how did you fix this?

I've hard-coded the serial device and speed in gmc320.c already, and I have verified I can talk to the unit via a python script.

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun gmc320 (no readiness notification)
s6-supervise gmc320: warning: unable to spawn ./run (waiting 60 seconds): Permission denied
